//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_Login
    {
        public long Id_Empleado { get; set; }
        public string Usuario { get; set; }
        public string Pwd { get; set; }
        public Nullable<System.DateTime> Ultimo_Acceso { get; set; }
        public Nullable<bool> Sesion_Activa { get; set; }
        public int Permisos { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual ctl_Empleado ctl_Empleado { get; set; }
    }
}
