//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_Nomina
    {
        public long Id_Empleado { get; set; }
        public string Sueldo { get; set; }
        public long Dias_Vacaciones { get; set; }
        public string Bono_Monto { get; set; }
        public Nullable<long> Dias_Asignados { get; set; }
        public Nullable<long> Dias_SAginacion { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ctl_Empleado ctl_Empleado { get; set; }
    }
}
