//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_WorkTime
    {
        public long id_WT { get; set; }
        public Nullable<long> id_Cliente { get; set; }
        public long Id_Empleado { get; set; }
        public long Id_Proyecto { get; set; }
        public Nullable<long> Dias_Laborados { get; set; }
        public Nullable<long> Horas_Laboradas { get; set; }
        public string Asignacion_SAP { get; set; }
        public string Id_Cargo { get; set; }
        public string Fecha_Carga { get; set; }
        public Nullable<bool> estatus { get; set; }
    }
}
