//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_Empleado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ctl_Empleado()
        {
            this.ctl_Proyecto = new HashSet<ctl_Proyecto>();
        }
    
        public long Id_empleado { get; set; }
        public string Nombre { get; set; }
        public string ApellidoP { get; set; }
        public string ApellidoM { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Calle { get; set; }
        public string NumExt { get; set; }
        public string NumInt { get; set; }
        public string Colonia { get; set; }
        public string Ciudad { get; set; }
        public string Tel_emergencia { get; set; }
        public string Contacto_emergencia { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<long> VacacionesN { get; set; }
        public string IMSS { get; set; }
        public string CURP { get; set; }
        public string INE_N { get; set; }
        public string Pasaporte_N { get; set; }
        public long Id_SAP { get; set; }
        public string Email { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ctl_Login ctl_Login { get; set; }
        public virtual ctl_Nomina ctl_Nomina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ctl_Proyecto> ctl_Proyecto { get; set; }
    }
}
