//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_Dia
    {
        public long id_Dia { get; set; }
        public long idEmpleado { get; set; }
        public System.DateTime cargaxDiaI { get; set; }
        public string horaI { get; set; }
        public decimal totHoras { get; set; }
        public string Explicacion { get; set; }
        public System.DateTime cargaxDiaF { get; set; }
        public string horaF { get; set; }
        public string titulo { get; set; }
        public string serviceO { get; set; }
    }
}
