//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_ContactosCliente
    {
        public long Id_Cliente { get; set; }
        public string Contacto { get; set; }
    
        public virtual ctl_Cliente ctl_Cliente { get; set; }
    }
}
