//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_Proyecto
    {
        public long Id_Proyecto { get; set; }
        public long Id_Cliente { get; set; }
        public long Id_Empleado { get; set; }
        public string Nombre_Proyecto { get; set; }
        public long Dias_Asignados { get; set; }
        public long Horas_Asignadas { get; set; }
        public string Costo_Dia { get; set; }
        public string Costo_Tiempo { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public bool Estatus { get; set; }
    
        public virtual ctl_Cliente ctl_Cliente { get; set; }
        public virtual ctl_Empleado ctl_Empleado { get; set; }
    }
}
