//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WFRXRC.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ctl_SAP
    {
        public long id_ctlSap { get; set; }
        public long Id_Empleado { get; set; }
        public long Id_SAP { get; set; }
        public string Mes { get; set; }
        public string Servicio { get; set; }
        public string Ubicacion { get; set; }
        public string Desc_CRM { get; set; }
        public long Id_Cliente { get; set; }
        public string CW { get; set; }
        public string Fecha_Asignacion { get; set; }
        public string Responsable_SAP { get; set; }
        public long Cantidad_Dias { get; set; }
        public string Service_Order { get; set; }
        public long idWT { get; set; }
    
        public virtual ctl_Cliente ctl_Cliente { get; set; }
    }
}
